import Head from 'next/head'
import Image from 'next/image'
import { Title } from '../components/Title'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Política de Privacidade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title
          title='Política de privacidade'
        />
      </main>
    </div>
  )
}
