import Head from 'next/head'
import Image from 'next/image'
import { Footer } from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Política de Privacidade</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Política de privacidade</h1>
        <div>
          <p>A sua privacidade é importante para nós. É política do WhatToPlay respeitar a sua privacidade em relação a qualquer informação sua que possamos coletar no site, e outros sites que possuímos e operamos.</p>
          <p>Solicitamos informações pessoais apenas quando realmente precisamos delas para lhe fornecer um serviço. Fazemo-lo por meios justos e legais, com o seu conhecimento e consentimento. Também informamos por que estamos coletando e como será usado. </p>
          <p>Apenas retemos as informações coletadas pelo tempo necessário para fornecer o serviço solicitado. Quando armazenamos dados, protegemos dentro de meios comercialmente aceitáveis ​​para evitar perdas e roubos, bem como acesso, divulgação, cópia, uso ou modificação não autorizados.</p>
          <p>Não compartilhamos informações de identificação pessoal publicamente ou com terceiros, exceto quando exigido por lei.</p>
          <p>O nosso site pode ter links para sites externos que não são operados por nós. Esteja ciente de que não temos controle sobre o conteúdo e práticas desses sites e não podemos aceitar responsabilidade por suas respectivas
          </p>
          <p>Você é livre para recusar a nossa solicitação de informações pessoais, entendendo que talvez não possamos fornecer alguns dos serviços desejados.</p>
        </div>
        <strong>Esta política é efetiva a partir de Março/2022.</strong>
        <Footer />
      </main>
    </div>
  )
}
