import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import {AiFillLinkedin, AiFillInstagram} from 'react-icons/ai'
import {theme} from '../theme/theme'

import {
  Main,
  Container,
  P,
  Strong,
  Title,
  Footer,
  LogoContainer,
  SocialContainer
 } from '../styles/index'

export default function Home() {
  return (
    <Main>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Política de privacidade</title>
      </Head>
      <Container>
        <Title>Política de Privacidade</Title>
        <P>
          A sua privacidade é importante para nós. É política do PabloSilvaDev
          respeitar a sua privacidade em relação a qualquer informação sua
          que possamos coletar no aplicativo, e outros aplicativos que possuímos e operamos.
        </P>
        <P>
          Solicitamos informações pessoais apenas quando realmente precisamos delas para lhe fornecer um serviço. Fazemo-lo por meios justos e legais, com o seu conhecimento e consentimento. Também informamos por que estamos coletando e como será usado.
        </P>
        <P>
          Apenas retemos as informações coletadas pelo tempo necessário para fornecer o serviço solicitado. Quando armazenamos dados, protegemos dentro de meios comercialmente aceitáveis ​​para evitar perdas e roubos, bem como acesso, divulgação, cópia, uso ou modificação não autorizados.</P>
        <P>Não compartilhamos informações de identificação pessoal publicamente ou com terceiros, exceto quando exigido por lei.
        </P>
        <P>
          O nosso aplicativo pode ter links para aplicativos externos que não são operados por nós. Esteja ciente de que não temos controle sobre o conteúdo e práticas desses aplicativos e não podemos aceitar responsabilidade por suas respectivas
        </P>
        <P>
          Você é livre para recusar a nossa solicitação de informações pessoais, entendendo que talvez não possamos fornecer alguns dos serviços desejados.
        </P>
        <P>
          Ao utilizar nossa aplicação você automaticamente concorda com nossa política de privacidade.
        </P>
        <Strong>Esta política é efetiva a partir de Março/2022.</Strong>
      </Container>
      <Footer>
        <LogoContainer>
          <Image
            src='/favicon.ico'
            alt='PabloSilvaDev'
            width={32}
            height={32}
          />
          <P>
            Pablo Silva Dev - 2022
          </P>
        </LogoContainer>
        <SocialContainer>
          <a
            href='https://www.linkedin.com/in/pablo-silva-76b521156/'
            target='_blank norefereer'
          >
          <AiFillLinkedin
            color={theme.colors.secondary}
            size={24}
          />
          </a>
          <a
            href='https://www.instagram.com/pablosilva.dev/'
            target='_blank norefereer'
          >
          <AiFillInstagram
            color={theme.colors.secondary}
            size={24}
          />
          </a>
        </SocialContainer>
      </Footer>
    </Main>
  )
}
